services:
  go:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - neighborhood
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgis/postgis:17-3.5
    container_name: postgis
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - neighborhood
    restart: unless-stopped

networks:
  neighborhood:
    driver: bridge

volumes:
  postgis_data:
    driver: local